### ISSUE TITLE
Review/update page descriptions

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/book#210]
We should review the description for each top-level page and see if we can have them gel with one another.

- https://proudlyservingbook.com/about/
- https://proudlyservingbook.com/book/
- https://proudlyservingbook.com/contributors/
- https://proudlyservingbook.com/what-they-say/
- https://proudlyservingbook.com/news/

**Comment by MorganGriffin-BloomWorks** [comment]
**Big thoughts!**
Does the landing page seem a little too much like Proudly Serving is an organization or a company? I think it might. 

If you agree:

- We could make it more clear it’s a guide. Just using the word “guide” might be enough.
- I know you might hate it, but what about “A guide for public service in the digital age.”
- Consider that “People” as a tab may add to the impression — feels like it could be the “Our team” page for employees. So what about “Contributors” or “Authors”?

**Book vs Contents**
So basically, we’ve got 2 different tabs presenting the book in 2 different formats. That makes sense for us but maybe not as we’re shifting more toward public presentation. People will wonder what the difference is between Contents and the Book. And as of now, there isn’t actually a book.

Suggestions: 

- Remove Book tab and move the “download/view the MS” to the bottom of the Contents page. This way, we’re presenting the google doc as an alternative format of what’s on Contents (I’m guessing most people won’t use it, but available if they want it).
- Later, when there is a book, we could add a new tab called “Order the book” or some such. 

**What they say**
For now, consider folding this into About. All 4 authors worked on the project, so it’s really “what we say.” 
When we get outside reviewers, we could add back in. “What they’re saying” feels more right than “What they say” — the first has the vibe of _psst, word on the street is_…  vs. _conventional wisdom_

Possible tweaked IA

Contents
- Read the guide [I know this leads with a verb and the rest don’t, but maybe okay]
Contributors
- The people who created Proudly Serving
About 
- How we got here 
News
- Updates on the project 
Whoops
- Something went wrong

For later:
What they’re saying (Hold back for now)
- See accolades/feedback from our peers
Order the book
- Buy a printed copy of Proudly Serving

**Comment by MorganGriffin-BloomWorks** [comment]
Updates!

### About
- Current description: Proudly Serving is a playbook helping governments build people-centered digital public services.
- Notes: The description is too close to the text immediately below in the opening section: "Proudly Serving is a guide to building people-centered digital public services."
- Suggestion: Reduce duplication by
    - Deleting current description and replacing with "Proudly Serving is a guide to building people-centered digital public services."
    - Remove that sentence from the first section of the text, so it just starts with Purpose

### Book
- Current description: Get the Proudly Serving book.
- Notes: Don't need to repeat "Proudly Serving" since it's prominent on the page.
- Recommendation: Change to "Read the book" for now. When a print edition is available, change to "Order the book."

### Contributors
- Current description: The people who created Proudly Serving.
- Notes: Good! Stet!

### What they're saying
- Current description: What they're saying about Proudly Serving.
- Notes: Description repeats the name of the page.
- Recommendation: Change to "Feedback from our peers" (or something like that). 

### News
- Current description: "Latest Proudly Serving updates."
- Notes: Don't need to repeat "Proudly Serving" since it's prominent on the page.
- Recommendation: Change to "Latest updates on the project."
